### ISSUE TITLE
support for custom pod DNS name 

### ISSUE THREAD

**Issue by guptaarvindk** [mongodb/mongodb-enterprise-kubernetes#56]
When deploying ops manager via CRD, the operator assumes that cluster pod dns is "cluster.local", which may not be a correct assumption in all scenarios. Instead of assuming cluster pod dns to be static value "cluster.local", please provide a configuration option in CR so that the name of the cluster can be passed along and can be used when accessing services by full fqdn.

for example, name of mongodb URI for application database used is 

    - name: OM_PROP_mongo_mongoUri
      value: mongodb://mongodb-ops-manager:kdiGmXWyfi5s@myopsmgr-db-0.myopsmgr-db-svc.my-mongo.svc.cluster.local:27017,myopsmgr-db-1.myopsmgr-db-svc.my-mongo.svc.cluster.local:27017,myopsmgr-db-2.myopsmgr-db-svc.my-mongo.svc.cluster.local:27017/?authMechanism=SCRAM-SHA-1&authSource=admin&connectTimeoutMS=20000&replicaSet=myopsmgr-db&serverSelectionTimeoutMS=20000

But my cluster pod DNS could myudomain.com, in that case opsmanager won't be able to connect to the database.  It needs to be configurable so that I can specify my pod DNS for the cluster and operator fills in the correct value for URI.

**Comment by BenElgar** [comment]
Hi! For this purpose you can use the `clusterName` field as specified here: https://docs.mongodb.com/kubernetes-operator/master/reference/k8s-operator-specification/#spec.clusterName

**Comment by guptaarvindk** [comment]
Thanks @BenElgar , I redeplyed the ops manager with above setting. So now my ops manager yamls is as follows:
`$ kube get opsmanager -n my-mongo -o yaml
apiVersion: v1
items:
- apiVersion: mongodb.com/v1
  kind: MongoDBOpsManager
  metadata:
    creationTimestamp: "2019-12-19T19:20:25Z"
    generation: 100
    name: myopsmgr
    namespace: my-mongo
    resourceVersion: "1985003"
    selfLink: /apis/mongodb.com/v1/namespaces/my-mongo/opsmanagers/myopsmgr
    uid: 7dbb6fdc-ceba-47b7-be00-d19320edb700
  spec:
    adminCredentials: opsmgradmin
    applicationDatabase:
      members: 3
      persistent: true
      podSpec: {}
      version: 4.0.7
    backup:
      enabled: false
    clusterName: xxx.yyy.com
    replicas: 1
    version: 4.2.0
  status:
    applicationDatabase:
      lastTransition: "2019-12-19T19:30:37Z"
      members: 3
      phase: Running
      type: ReplicaSet
      version: 4.0.7
    opsManager:
      lastTransition: "2019-12-19T19:30:30Z"
      message: Ops Manager is still starting
      phase: Reconciling
      url: http://myopsmgr-svc.my-mongo.svc.cluster.local:8080
      version: ""
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`

But you can see in status above that its still using ".cluster.local", Also below is the the yaml output of the actual mongo-opsmgr pod and you can see its using cluster.local

`spec:
  containers:
  - env:
    - name: OM_PROP_automation_versions_directory
      value: /mongodb-ops-manager/mongodb-releases/
    - name: OM_PROP_mms_centralUrl
      value: http://myopsmgr-svc.my-mongo.svc.cluster.local:8080
    - name: OM_PROP_mms_featureControls_enable
      value: "true"
    - name: OM_PROP_mongo_mongoUri
      value: mongodb://mongodb-ops-manager:Mfik7Rvnr-eh@myopsmgr-db-0.myopsmgr-db-svc.my-mongo.svc.cluster.local:27017,myopsmgr-db-1.myopsmgr-db-svc.my-mongo.svc.cluster.local:27017,myopsmgr-db-2.myopsmgr-db-svc.my-mongo.svc.cluster.local:27017/?authMechanism=SCRAM-SHA-1&authSource=admin&connectTimeoutMS=20000&replicaSet=myopsmgr-db&serverSelectionTimeoutMS=20000`

thanks

**Comment by antonlisovenko** [comment]
you are right @guptaarvindk, there's a bug in the code, tracking in CLOUDP-54817

**Comment by guptaarvindk** [comment]
Hi @antonlisovenko just checking if there is any update on this bug. Thanks,

**Comment by antonlisovenko** [comment]
hi @guptaarvindk , the fix is ready we plan the next release of the Operator by the end of January

**Comment by antonlisovenko** [comment]
This was fixed in Operator 1.4.2

**Comment by paulwilliamford** [comment]
ok so i am performing an intneral mindtickle right now and running this on my local machine - the ops manager dashboard resolves 192.168.99.101:35016 but the ops-manager-0-0-mms: still is configured for http://ops-manager-svc.mongodb.svc.cluster.local:8080 which does not resolve and overrides the ip port setting in the ops manager UI. How do i resolve this?
